/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app.suppliers.index'
import { Route as AppReceivingIndexRouteImport } from './routes/_app.receiving.index'
import { Route as AppPurchaseOrdersIndexRouteImport } from './routes/_app.purchase-orders.index'
import { Route as AppSuppliersIdRouteImport } from './routes/_app.suppliers.$id'
import { Route as AppReceivingIdRouteImport } from './routes/_app.receiving.$id'
import { Route as AppPurchaseOrdersIdRouteImport } from './routes/_app.purchase-orders.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivingIndexRoute = AppReceivingIndexRouteImport.update({
  id: '/receiving/',
  path: '/receiving/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIndexRoute = AppPurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIdRoute = AppSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivingIdRoute = AppReceivingIdRouteImport.update({
  id: '/receiving/$id',
  path: '/receiving/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIdRoute = AppPurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/payments': typeof AppPaymentsRoute
  '/products': typeof AppProductsRoute
  '/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/receiving/$id': typeof AppReceivingIdRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/receiving/': typeof AppReceivingIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/payments': typeof AppPaymentsRoute
  '/products': typeof AppProductsRoute
  '/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/receiving/$id': typeof AppReceivingIdRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/purchase-orders': typeof AppPurchaseOrdersIndexRoute
  '/receiving': typeof AppReceivingIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/_app/receiving/$id': typeof AppReceivingIdRoute
  '/_app/suppliers/$id': typeof AppSuppliersIdRoute
  '/_app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/_app/receiving/': typeof AppReceivingIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/payments'
    | '/products'
    | '/purchase-orders/$id'
    | '/receiving/$id'
    | '/suppliers/$id'
    | '/purchase-orders/'
    | '/receiving/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/payments'
    | '/products'
    | '/purchase-orders/$id'
    | '/receiving/$id'
    | '/suppliers/$id'
    | '/purchase-orders'
    | '/receiving'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/payments'
    | '/_app/products'
    | '/_app/purchase-orders/$id'
    | '/_app/receiving/$id'
    | '/_app/suppliers/$id'
    | '/_app/purchase-orders/'
    | '/_app/receiving/'
    | '/_app/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receiving/': {
      id: '/_app/receiving/'
      path: '/receiving'
      fullPath: '/receiving/'
      preLoaderRoute: typeof AppReceivingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders/': {
      id: '/_app/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/$id': {
      id: '/_app/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AppSuppliersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receiving/$id': {
      id: '/_app/receiving/$id'
      path: '/receiving/$id'
      fullPath: '/receiving/$id'
      preLoaderRoute: typeof AppReceivingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders/$id': {
      id: '/_app/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AppPurchaseOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPurchaseOrdersIdRoute: typeof AppPurchaseOrdersIdRoute
  AppReceivingIdRoute: typeof AppReceivingIdRoute
  AppSuppliersIdRoute: typeof AppSuppliersIdRoute
  AppPurchaseOrdersIndexRoute: typeof AppPurchaseOrdersIndexRoute
  AppReceivingIndexRoute: typeof AppReceivingIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProductsRoute: AppProductsRoute,
  AppPurchaseOrdersIdRoute: AppPurchaseOrdersIdRoute,
  AppReceivingIdRoute: AppReceivingIdRoute,
  AppSuppliersIdRoute: AppSuppliersIdRoute,
  AppPurchaseOrdersIndexRoute: AppPurchaseOrdersIndexRoute,
  AppReceivingIndexRoute: AppReceivingIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
